# Generated by Django 4.0.2 on 2022-03-04 18:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.AutoField(db_column='ID', primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, db_column='name', max_length=255, null=True)),
                ('description', models.CharField(blank=True, db_column='description', max_length=2550, null=True)),
                ('numberOfPages', models.IntegerField(blank=True, db_column='numberOfPages', default=1, null=True)),
                ('author', models.CharField(blank=True, db_column='author', max_length=255, null=True)),
                ('price', models.IntegerField(blank=True, db_column='price', default=10000, null=True)),
                ('image', models.CharField(blank=True, db_column='image', max_length=255, null=True)),
            ],
            options={
                'db_table': 'Book',
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(db_column='ID', primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, db_column='name', max_length=255, null=True)),
            ],
            options={
                'db_table': 'Category',
            },
        ),
        migrations.CreateModel(
            name='PublishingCompany',
            fields=[
                ('id', models.AutoField(db_column='ID', primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, db_column='name', max_length=255, null=True)),
                ('address', models.CharField(blank=True, db_column='address', max_length=255, null=True)),
                ('phoneNumber', models.CharField(blank=True, db_column='phoneNumber', max_length=11, null=True)),
                ('email', models.CharField(blank=True, db_column='email', max_length=100, null=True)),
            ],
            options={
                'db_table': 'PublishingCompany',
            },
        ),
        migrations.CreateModel(
            name='BookItem',
            fields=[
                ('id', models.AutoField(db_column='ID', primary_key=True, serialize=False)),
                ('discount', models.FloatField(blank=True, db_column='discount', default=0, max_length=255, null=True)),
                ('startDay', models.DateTimeField(auto_now_add=True, db_column='startDay', max_length=255, null=True)),
                ('endDay', models.DateTimeField(auto_now_add=True, db_column='endDay', max_length=255, null=True)),
                ('image', models.CharField(blank=True, db_column='image', max_length=255, null=True)),
                ('bookID', models.ForeignKey(db_column='bookID', on_delete=django.db.models.deletion.CASCADE, to='shop.book')),
            ],
            options={
                'db_table': 'BookItem',
            },
        ),
        migrations.AddField(
            model_name='book',
            name='categoryID',
            field=models.ForeignKey(db_column='categoryID', on_delete=django.db.models.deletion.CASCADE, to='shop.category'),
        ),
        migrations.AddField(
            model_name='book',
            name='publishingCompanyID',
            field=models.ForeignKey(db_column='publishingCompanyID', on_delete=django.db.models.deletion.DO_NOTHING, to='shop.publishingcompany'),
        ),
    ]
